apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200

  - name: Mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    basicAuth: false
    isDefault: true
    orgId: 1
    jsonData:
      prometheusType: mimir
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "1"

  - name: Pyroscope
    type: phlare           # "phlare" is used for both Pyroscope and Phlare in Grafana
    access: proxy
    url: http://pyroscope:4040
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      backendType: pyroscope
      minStep: '15s'
